sifen:
  timeout: 30000

server:
  port: ${PORT:8080}


spring:
  application:
    name: sifen-api-java

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:sifenboot}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:password}
    driver-class-name: org.postgresql.Driver

  # --- AGREGAR ESTO PARA THYMELEAF ---
  thymeleaf:
    cache: false
    prefix: file:./web/
    suffix: .html
    mode: HTML
    check-template-location: true
  # -----------------------------------

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:noauth}

  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC

  flyway:
    enabled: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

  web:
    resources:
      static-locations:
        - file:./web/
  mvc:
    static-path-pattern: /**


  # Quitamos el exclude para que Spring active JDBC automáticamente
  autoconfigure:
    exclude: []

jwt:
  secret: ${JWT_SECRET:clave_secreta_para_desarrollo_de_al_menos_32_caracteres}
  expiration: ${JWT_EXPIRATION:86400000}

logging:
  level:
    org.springdoc: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot: INFO
    com.sifen: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    url: /v3/api-docs
    path: /swagger-ui.html
    tryItOutEnabled: true
  show-actuator: true